server:
  port: 8080

spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:database-post-changelog.xml
    default-schema: ${DB_SCHEMA:post}

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/skillbox
    username: ${DB_USERNAME:post}
    password: ${DB_PASSWORD:post}
    driverClassName: org.postgresql.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: ${DB_SCHEMA:post}
    open-in-view: false

  kafka:
    consumer:
      group-id: event.1
    bootstrap-servers: 82.202.214.42:9094

logging:
  level:
    org.springframework.web: info
    org.hibernate: error
    ru.skillbox: info

springdoc:
  api-docs:
    enabled: true
    path: '/api/v1/post/v3/api-docs'
  swagger-ui:
    path: '/api/v1/post/swagger-ui'
    doc-expansion: none
    disable-swagger-default-url: true

