spring:
  boot:
    admin:
      client:
        enabled: false
  cloud:
    kubernetes:
      config:
        enabled: false
      reload:
        monitoring-config-maps: false
  liquibase:
    enabled: true
    drop-first: true
    default-schema: post
    liquibase-schema: post

  datasource:
    username: test
    password: test
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;INIT=CREATE SCHEMA IF NOT EXISTS post\;CREATE SCHEMA IF NOT EXISTS account