server:
  port: 8080

spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:database-post-changelog.xml
    default-schema: ${DB_SCHEMA:post}

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-service}:5432/skillbox
    username: ${DB_USERNAME:post}
    password: ${DB_PASSWORD:post}
    driverClassName: org.postgresql.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: ${DB_SCHEMA:post}
    open-in-view: false

  cache:
    type: simple
  redis.host: redis
  data:
    redis:
      repositories.enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
