spring:
  boot:
    admin:
      client:
        enabled: false
  cloud:
    kubernetes:
      config:
        enabled: false
      reload:
        monitoring-config-maps: false
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/skillbox
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:database-post-changelog.xml
    default-schema: post
    liquibase-schema: post

